# Name
**Gabe Roeloffs**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE**

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [4]:
# Make an array a of size 6 × 4 where every element is a 2.
import numpy as np

a = np.full((6,4), 2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [5]:
# Make an array b of size 6 × 4 that has 3 on the leading diagonal and 1 everywhere else.
b = np.full((6,4), 1)
np.fill_diagonal(b, 3)
print(b)


[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Exercise 3

In [6]:
# Can you multiply these two matrices together? Why does a * b work, but not dot(a,b)?
print(a * b)

# dot(a, b) does not work because the number of rows in a is not equivalent to the number
# of columns in b

[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 4

In [7]:
# Compute dot(a.transpose(),b) and dot(a,b.transpose()). Why are the results different shapes?

print(np.dot(a.transpose(), b))
print(np.dot(a, b.transpose()))

# Because in the first case, each row of a is multiplied against each column of b.
# Since there are four rows in a because it is transposed, it is multiplied against four columns,
# yielding a 4x4 matrix. The same is true for the second case, except with six rows multiplied against six columns.

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]
[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]


## Exercise 5

In [8]:
# Write a function that prints some output on the screen and make sure you can run it in the programming environment that you are using.
def hello_there():
    print("hello there")
hello_there()

hello there


## Exercise 6

In [9]:
# Now write one that makes some random arrays and prints out their sums, the mean value, etc.

def test_func():
    rand1 = np.random.rand(5,5)
    rand2 = np.random.rand(5,5)

    print("sum")
    print(np.sum(rand1))
    print("mean value")
    print(np.mean(rand1))
    
test_func()



sum
13.917766824360287
mean value
0.5567106729744115


## Exercise 7

In [14]:
# Write a function that consists of a set of loops that run through an array and count the number of ones in it. Do the same thing using the where() function (use info(where) to find out how to use it).
def num_ones_naive(input_array):
    count = 0
    for i in range(0, input_array.shape[0]):
        for j in range(0, input_array.shape[1]):
            if input_array[i][j] == 1:
                count += 1
                
    return count

def num_ones_fast(input_array):
    return len(np.where(input_array==1)[0])

a = np.full((4,4), 1)
print(num_ones_naive(a))
print(num_ones_fast(a))


16
16


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [23]:
import pandas as pd

# Make an array a of size 6 × 4 where every element is a 2.
dfa = pd.DataFrame(np.full((6,4), 2))
print(dfa)

   0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2


## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [28]:
# YOUR SOLUTION HERE
b = np.full((6,4), 1)
np.fill_diagonal(b, 3)
dfb = pd.DataFrame(b)
print(dfb)

   0  1  2  3
0  3  1  1  1
1  1  3  1  1
2  1  1  3  1
3  1  1  1  3
4  1  1  1  1
5  1  1  1  1


## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [29]:
# YOUR SOLUTION HERE
c = pd.DataFrame(dfa.values*dfb.values, columns=dfa.columns, index=dfa.index)
print(c)

   0  1  2  3
0  6  2  2  2
1  2  6  2  2
2  2  2  6  2
3  2  2  2  6
4  2  2  2  2
5  2  2  2  2


## Exercise 11
Repeat exercise A.7 using a dataframe.

In [45]:
# Write a function that consists of a set of loops that run through an array and count the number of ones in it. Do the same thing using the where() function (use info(where) to find out how to use it).
def num_ones_naive(input_df):
    count = 0
    for i in range(0, input_df.shape[0]):
        for j in range(0, input_df.shape[1]):
            if input_df.iloc[i][j] == 1:
                count += 1
                
    return count

def num_ones_fast(input_df):
    input_df.where(input_df==1, inplace=True)
    return len(input_df[0]) * len(input_df[1])

a = pd.DataFrame(np.full((4,4), 1))
print(num_ones_naive(a))
print(num_ones_fast(a))


16
16


## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [48]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [56]:
## YOUR SOLUTION HERE
titanic_df['pclass']

sex
female    1
male      1
female    1
male      1
female    1
         ..
female    3
female    3
male      3
male      3
male      3
Name: pclass, Length: 1309, dtype: int64

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [72]:
## YOUR SOLUTION HERE
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df.set_index('sex',inplace=True)
print(titanic_df.index.value_counts())


male      843
female    466
Name: sex, dtype: int64


## Exercise 14
How do you reset the index?

In [73]:
## YOUR SOLUTION HERE

In [75]:
titanic_df.reset_index()

sex  pclass  survived  \
0     female       1         1   
1       male       1         1   
2     female       1         0   
3       male       1         0   
4     female       1         0   
...      ...     ...       ...   
1304  female       3         0   
1305  female       3         0   
1306    male       3         0   
1307    male       3         0   
1308    male       3         0   

                                                 name      age  sibsp  parch  \
0                       Allen, Miss. Elisabeth Walton  29.0000      0      0   
1                      Allison, Master. Hudson Trevor   0.9167      1      2   
2                        Allison, Miss. Helen Loraine   2.0000      1      2   
3                Allison, Mr. Hudson Joshua Creighton  30.0000      1      2   
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000      1      2   
...                                               ...      ...    ...    ...   
1304                             Zabour, Miss. Hileni  14.5000      1      0   
1305                            Zabour, Miss. Thamine      NaN      1      0   
1306                        Zakarian, Mr. Mapriededer  26.5000      0      0   
1307                              Zakarian, Mr. Ortin  27.0000      0      0   
1308                               Zimmerman, Mr. Leo  29.0000      0      0   

      ticket      fare    cabin embarked boat   body  \
0      24160  211.3375       B5        S    2    NaN   
1     113781  151.5500  C22 C26        S   11    NaN   
2     113781  151.5500  C22 C26        S  NaN    NaN   
3     113781  151.5500  C22 C26        S  NaN  135.0   
4     113781  151.5500  C22 C26        S  NaN    NaN   
...      ...       ...      ...      ...  ...    ...   
1304    2665   14.4542      NaN        C  NaN  328.0   
1305    2665   14.4542      NaN        C  NaN    NaN   
1306    2656    7.2250      NaN        C  NaN  304.0   
1307    2670    7.2250      NaN        C  NaN    NaN   
1308  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 14 columns]